CREATE TABLE IF NOT EXISTS labels (
  name TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO labels (name)
SELECT DISTINCT UNNEST(labels) AS name
FROM notes
WHERE ARRAY_LENGTH(labels, 1) IS NOT NULL
ON CONFLICT (name) DO NOTHING;
